### ISSUE TITLE
Introduce Keyboard Shortcut and Floating Button for Canceling AI Generation

### ISSUE THREAD

**Issue by jjroelofs** [dxpr/ckeditor5-ai-agent#11]
Here is the updated full issue, incorporating our agreements and suggestions:

---

## Why are we doing this work
To improve the user experience when interacting with the AI assistant plugin in CKEditor 5, particularly when generation takes longer than expected. Providing a keyboard shortcut (Cmd/Ctrl + Backspace) and a hoverable cancel button ensures users can quickly and easily cancel AI generation, preventing frustration and improving workflow efficiency, especially in cases of fast content printing or on different screen sizes.

![image](https://github.com/user-attachments/assets/9cd8b48e-0bff-4dde-aecb-33f9897a9e5c)

Taking the idea and design from Cursor AI UI:

![ezgif-2-145670819b](https://github.com/user-attachments/assets/edc9261e-5d0a-4b8b-9265-aa803d2ba1d4)

## Relevant links
- [CKEditor 5 Documentation - Handling Keystrokes](https://ckeditor.com/docs/ckeditor5/latest/framework/tutorials/crash-course/keystrokes.html#adding-shortcut-information-to-the-accessibility-help-dialog)
- [Accessibility Help Dialog - Displaying Keyboard Shortcuts](https://ckeditor.com/docs/ckeditor5/latest/features/accessibility.html#displaying-keyboard-shortcuts-in-the-editor)

## Requirements
- Implement the Cmd/Ctrl + Backspace keyboard shortcut to cancel AI generation.
- Introduce a floating "Cancel generation" button that appears after 2 seconds of generation time and behaves responsively across different screen sizes:
  - **On large screens**: The button should anchor to the text editor block.
  - **On small screens**: The button should anchor to the viewport to ensure it’s always accessible.
  - On mobile devices, ensure the button is large enough for touch interaction.
- The button text should include the appropriate keyboard shortcut icon for the platform:
    - MacOS: option button icon.
    - Windows: Alt or Ctrl button icon.
    - Other/mobile: No keyboard shortcut, only "Cancel."
- Update the Accessibility help dialog to include the new shortcut under the "Content editing keystrokes" section.
- Ensure the button’s design matches the provided reference, and its visibility is persistent until the user cancels or the generation finishes.
- Must be tested to work on:
  - Windows Chrome
  - MacOS Chrome
  - Windows Firefox
  - iOS Safari
  - Android Chrome
  - Samsung mobile internet browser
  
## Implementation plan

1. **Implement the Cancel Generation Shortcut**
   - Use the `editor.keystrokes.set()` method from CKEditor 5 API to implement the `Ctrl + Backspace` keyboard shortcut. CKEditor will automatically translate this to `Cmd + Backspace` on macOS.
   - Example code:
     ```javascript
     editor.keystrokes.set( 'Ctrl+Backspace', (event, cancel) => {
         editor.execute('cancelGeneration'); // Logic to cancel generation
         cancel();
     });
     ```

2. **Add the Hoverable Cancel Button**
   - Introduce a hoverable "Cancel generation" button that appears after 2 seconds of AI generation.
   - **Responsive behavior:**
     - For **larger screens** (desktop/tablets), anchor the button to the text editor block, positioning it within the editor for context.
     - For **smaller screens** (mobile/small tablets), anchor the button to the viewport so it remains visible and easy to access at all times.
     - Use CSS media queries for dynamic switching:
       ```css
       @media (min-width: 768px) {
           /* Anchor to editor block for larger screens */
           .cancel-button {
               position: absolute; /* Positioned relative to the editor block */
               top: 10px;
               right: 10px;
           }
       }

       @media (max-width: 767px) {
           /* Anchor to viewport for smaller screens */
           .cancel-button {
               position: fixed; /* Positioned relative to the viewport */
               bottom: 20px;
               right: 20px;
           }
       }
       ```
   - Ensure the button’s design matches the provided mockup and remains clickable throughout the AI generation process.
   - Adjust the button's label based on the platform:
     - MacOS: Include the option key icon.
     - Windows: Include the Alt or Ctrl key icon.
     - Other/mobile: Display just "Cancel" without any keyboard shortcut.

3. **Update the Accessibility Help Dialog**
   - Use `editor.accessibility.addKeystrokeInfos` to include the new shortcut in the accessibility help dialog.
   - Example code:
     ```javascript
     const t = editor.t;

     editor.accessibility.addKeystrokeInfos({
         keystrokes: [
             {
                 label: t('Cancel AI generation'),
                 keystroke: 'Ctrl+Backspace'  // Automatically converted to Cmd+Backspace on macOS
             }
         ]
     });
     ```

4. **Documentation and Testing**
   - Update the relevant documentation to include the new keyboard shortcut and cancel button.
   - Ensure both the shortcut and button are tested across all supported platforms and devices, covering responsive behaviors for both large and small screens.

## How to View the Keyboard Info Panel
The keyboard info panel can be viewed by pressing `Option + 0` on a MacBook or the equivalent Windows shortcut. Alternatively, it can be accessed by clicking the Accessibility info panel button at this [URL](https://ckeditor.com/docs/ckeditor5/latest/features/accessibility.html#displaying-keyboard-shortcuts-in-the-editor).
